name: clean_architecture_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  intl: ^0.18.1
  floor: ^1.4.2
  retrofit: ^4.0.3
  flutter_hooks: ^0.20.3
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  clean_architecture_scaffold: ^0.0.7
  go_router: ^11.1.4
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.0.0
  pretty_dio_logger: ^1.3.1
  live_activities: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: any
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
